import os
import random
import shutil

# --- 配置 ---
POSTS_DIR = 'posts'
NUM_POSTS = 30  # 生成文章数量

# 标签池
TAGS = [
    "Unity", "Shader", "VFX", "GameDesign", "C#", 
    "Modeling", "AI", "Physics", "Rendering", "Networking"
]

TITLES = [
    "The Basics of Unity Physics", "Advanced Shader Techniques", "Character Controller Guide",
    "Multiplayer Networking Logic", "Optimizing Game Performance", "VFX Graph Tutorial",
    "Procedural Generation Algorithms", "AI Pathfinding with A*", "Lighting and Baking",
    "Post-processing Stack Overview"
]

def clear_posts():
    if os.path.exists(POSTS_DIR):
        shutil.rmtree(POSTS_DIR)
    os.makedirs(POSTS_DIR)
    print(f"Cleared {POSTS_DIR}")

def generate_post(index):
    title = f"{random.choice(TITLES)} {index+1}"
    
    # 随机选 1-3 个标签
    num_tags = random.randint(1, 3)
    selected_tags = random.sample(TAGS, num_tags)
    
    # 构造 #标签 格式字符串 (例如 "#Unity #Shader")
    tags_str = " ".join([f"#{t}" for t in selected_tags])
    
    # 随机生成一些链接目标
    links = []
    if index > 0:
        # 链接到之前的文章
        target_id = f"post_{random.randint(0, index-1)}"
        links.append(f"Refer to [[{target_id}]] for more info.")
        links.append(f"Also check out [Previous Post](./{target_id}.md).")

    content = f"""---
title: {title}
date: 2024-01-{random.randint(1,30):02d}
---

# {title}

This is a generated post content for testing purposes.

{tags_str}

## Overview
Here we discuss **{selected_tags[0]}** and its applications.

{' '.join(links)}

## Details
Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

> Generated by seed_posts.py
"""
    
    filename = f"post_{index}.md"
    filepath = os.path.join(POSTS_DIR, filename)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return filename

def main():
    clear_posts()
    print(f"Generating {NUM_POSTS} posts...")
    for i in range(NUM_POSTS):
        generate_post(i)
    print("Done. Run 'start_blog.py' to rebuild index.")

if __name__ == '__main__':
    main()
