import os
import random
import shutil

# --- 配置 ---
POSTS_DIR = 'posts'
NUM_POSTS = 30  # 生成文章数量

# 标签池
TAGS = [
    "Unity", "Shader", "VFX", "GameDesign", "C#", 
    "Modeling", "AI", "Physics", "Rendering", "Networking"
]

TITLES = [
    "The Basics of Unity Physics", "Advanced Shader Techniques", "Character Controller Guide",
    "Multiplayer Networking Logic", "Optimizing Game Performance", "VFX Graph Tutorial",
    "Procedural Generation Algorithms", "AI Pathfinding with A*", "Lighting and Baking",
    "Post-processing Stack Overview"
]

def clear_posts():
    if os.path.exists(POSTS_DIR):
        shutil.rmtree(POSTS_DIR)
    os.makedirs(POSTS_DIR)
    print(f"Cleared {POSTS_DIR}")

def generate_posts(num_posts):
    # 1. 预先生成所有标题
    posts_meta = []
    for i in range(num_posts):
        title = f"{random.choice(TITLES)} {i+1}"
        filename = f"post_{i}.md"
        posts_meta.append({
            "id": i,
            "title": title,
            "filename": filename
        })
        
    # 2. 生成文件
    for i, meta in enumerate(posts_meta):
        # 随机选 1-3 个标签
        num_tags = random.randint(1, 3)
        selected_tags = random.sample(TAGS, num_tags)
        tags_str = " ".join([f"#{t}" for t in selected_tags])
        
        # 随机生成 0-3 个链接
        num_links = random.randint(0, 3)
        links_content = []
        
        # 候选列表：除了自己意外的所有文章
        candidates = [p for p in posts_meta if p['id'] != i]
        
        if candidates and num_links > 0:
            targets = random.sample(candidates, min(num_links, len(candidates)))
            
            links_content.append("\n## Related Posts")
            for target in targets:
                # 格式: [Target Title](./post_X.md)
                link_text = f"- Check this out: [{target['title']}](./{target['filename']})"
                links_content.append(link_text)
                
        links_str = "\n".join(links_content)

        content = f"""---
title: {meta['title']}
date: 2024-01-{random.randint(1,30):02d}
---

# {meta['title']}

This is a generated post content for testing purposes.

{tags_str}

## Overview
Here we discuss **{selected_tags[0]}** and its applications.

## Details
Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

{links_str}

> Generated by seed_posts.py
"""
    
        filepath = os.path.join(POSTS_DIR, meta['filename'])
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        # print(f"Generated {meta['filename']}")

def main():
    clear_posts()
    print(f"Generating {NUM_POSTS} posts...")
    generate_posts(NUM_POSTS)
    print("Done. Run 'start_blog.py' to rebuild index.")

if __name__ == '__main__':
    main()
